-- ==========================
-- fichier : ddl_marais_salants.sql
-- base : Marais Salant
-- auteur(s) : Louis Butraud & Thomas Dubos
-- date : 15/12/2014
-- role : création des tables
-- resultat dans : nom_du_fichier.out
--=============================

CREATE TABLE PROPRIETAIRE(
IDPRO NUMBER(4) NOT NULL,
NOMPRO VARCHAR2(50) NOT NULL,
PRENOMPRO VARCHAR2(50) NOT NULL,
CONSTRAINT PK_PROPRIETAIRE
			PRIMARY KEY (IDPRO)
);


CREATE TABLE MARAIS(
IDMAR NUMBER(4) NOT NULL,
NOMMAR VARCHAR2(50) NOT NULL,
ADRMAR VARCHAR2(250) NULL,
CONSTRAINT PK_MARAIS
			PRIMARY KEY (IDMAR)
CONSTRAINT UNK_MARAIS
		UNIQUE (NOMMAR)
);


CREATE TABLE PROPRIETE(
IDPRO NUMBER(4)NOT NULL,
IDMAR NUMBER(4) NOT NULL,
CONSTRAINT PK_PROPRIETE
		PRIMARY KEY(IDPRO,IDMAR)
);


CREATE TABLE SAUNIER(
IDSAU NUMBER (4) NOT NULL,
NOMSAU VARCHAR(50) NOT NULL,
PRENOMSAU VARCHAR(50) NOT NULL,
CONSTRAINT PK_SAUNIER
		PRIMARY KEY(IDSAU)
);


CREATE TABLE CARREAU(
IDCAR NUMBER(4) NOT NULL,
IDMAR NUMBER(4) NOT NULL,
NUMEMP NUMBER(3) NOT NULL,
CONSTRAINT PK_CARREAU
		PRIMARY KEY(IDCAR)
CONSTRAINT UNK_CARREAU
		UNIQUE (IDMAR,NUMEMP)
);


CREATE TABLE RECOLTE(
IDREC NUMBER(4) NOT NULL,
IDCAR NUMBER(4) NOT NULL,
IDSAU NUMBER (4) NOT NULL,
DATEREC DATE NOT NULL,
TYPESEL CHAR(5) NOT NULL,
QTESEL NUMBER(5,3) NOT NULL,
CONSTRAINT PK_RECOLTE
		PRIMARY KEY(IDREC)
CONSTRAINT UNK_RECOLTE
		UNIQUE(IDCAR,IDSAU,DATEREC,TYPESEL)
);