-- ==========================
-- fichier : description_base_marais_salants.sql
-- base :
-- auteur(s) : Louis Butraud & Thomas Dubos
-- date :15/12/2014
-- role : description des tables.
-- projet : marais
-- resultat dans: nom_du_fichier.out // à renseigner si nécessaire
-- ==========================